
// Declare a new Item that shows various basic Items
// (it will be used in the top-level TabPanel of the Utility window)
//  It inherits from Column so will arrange child Items vertically and its
//  height will automatically accomodate all the children
SettingsTab : Row
{
    Column {
        spacing: 10
        Text {
            text: "Settings: "
            fontSize: 32
        }
        Row {
            Text {
                text: "Autonomous mode"
                fontSize: 24
            }
            CheckBox {
                id: autoCheckBox
                checked: false
            }
        }
        Row {
            Text {
                text: "Placement mode"
                fontSize: 24
            }
            ComboBox {
                id: placeComboBox
                options: ["Bracelet", "Poles"]
            }
        }
    }
}

