
// Declare a new Item that shows various basic Items
// (it will be used in the top-level TabPanel of the Utility window)
//  It inherits from Column so will arrange child Items vertically and its
//  height will automatically accomodate all the children
SettingsTab : Row
{
    Column {
        spacing: 10
        Text {
            text: "Settings: "
            fontSize: 32
        }
        Row {
            Text {
                text: "Autonomous mode"
                fontSize: 24
            }
            CheckBox {
                id: autoCheckBox
                checked: false
            }
            Text {
                text: "Words"
                fontSize: 20
            }
            ComboBox {
                id: AutoWords
                width: 175
                options: ["YASKAWA",
                          "AUTOMATION",
                          "MECHATRONICS",
                          "ROBOTICS",
                          "MACHINE",
                          "LABORATORY",
                          "FABULOUSNES`S",
                          "CONTROLLER",
                          "ALPHANUMERIC",
                          "PERSEVERANCE"]
            }
        }
        Row {
            Text {
                text: "Placement mode"
                fontSize: 24
            }
            ComboBox {
                id: placeComboBox
                options: ["Bracelet", "Poles"]
            }
        }
        Row {
            Rectangle { id: Open; width: 40; height: 40; radius: 5; color: "blue";Text{id: openText; centerIn: parent; text: "O"; color: "white"; fontSize: 24; fontWeight: Const.Bold}}
            Rectangle { id: Closed; width: 40; height: 40; radius: 5; color: "blue";Text{id: closeText; centerIn: parent; text: "C"; color: "white"; fontSize: 24; fontWeight: Const.Bold}}
        }
        Button {
            id: GPOpen
            text: "Open Gripper"
        }
        Button {
            id: GPClose
            text: "Close Gripper"
        }
        Row {
          align: Const.Bottom
          Item {
              width: 593
              height: 645
          }
          Button {
              id: MainButton
              text: "Main Tab"
          }
        }
    }
}

